[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
startCommand = "pip install -r requirements.txt && gunicorn django_project.wsgi --log-file -"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
