# Generated by Django 4.1.5 on 2023-01-27 00:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0002_delete_htmlmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Homepage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", tinymce.models.HTMLField()),
            ],
        ),
    ]
