# Generated by Django 4.1.5 on 2023-01-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_alter_page_handle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.CharField(
                default="\n        <p>\n            Our mission is to provide child-centered care focused on fostering children's creativity, educational development, \n            and independece. We provide a resource-rich, inclusive environment that allows each child to develop at his/her own pace.\n            Our classrooms are designed to give children room to grow and express themselves in a safe space.\n        </p>\n    ",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="handle",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("philosophy", "Our Philosophy"),
                    ("classrooms", "Classrooms"),
                    ("steam.", "S.T.E.A.M."),
                    ("preschool", "Preschool"),
                    ("school_age", "School Age"),
                    ("contact", "Contact"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
