# Generated by Django 4.1.5 on 2023-01-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_alter_page_content_alter_page_handle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.CharField(
                default="\n        <p>\n            Our mission is to provide child-centered care focused on fostering children's creativity, educational development, \n            and independece. We provide a resource-rich, inclusive environment that allows each child to develop at his/her own pace.\n            Our classrooms are designed to give children room to grow and express themselves in a safe space.\n        </p>\n    ",
                max_length=500000,
            ),
        ),
    ]
