# Generated by Django 4.1.5 on 2023-01-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_page_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="content",
        ),
        migrations.RemoveField(
            model_name="page",
            name="title",
        ),
    ]
