# Generated by Django 4.1.5 on 2023-01-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_remove_page_content_remove_page_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="content",
            field=models.CharField(default=True, max_length=5000),
        ),
        migrations.AddField(
            model_name="page",
            name="title",
            field=models.CharField(default=True, max_length=200),
        ),
    ]
