# Generated by Django 4.1.5 on 2023-01-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_page_content_page_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.CharField(default="Content", max_length=5000),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(default="Title", max_length=200),
        ),
    ]
