# Generated by Django 4.1.5 on 2023-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_alter_page_content_alter_page_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="content2",
            field=models.CharField(default="Content2", max_length=500000),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.CharField(default="Content", max_length=500000),
        ),
    ]
