# Generated by Django 4.1.5 on 2023-01-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_rename_content2_page_content_secondary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="handle",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("philosophy", "Our Philosophy"),
                    ("classrooms", "Classrooms"),
                    ("steam", "S.T.E.A.M."),
                    ("preschool", "Preschool"),
                    ("school_age", "School Age"),
                    ("contact", "Contact"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
