# Generated by Django 4.1.5 on 2023-01-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0016_alter_page_handle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
