# Generated by Django 4.1.5 on 2023-01-29 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_alter_page_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="image",
        ),
    ]
