# Generated by Django 4.1.5 on 2023-02-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0019_alter_page_handle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(blank=True, max_length=254, null=True)),
                ("lname", models.CharField(blank=True, max_length=254, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=254, null=True)),
                ("children", models.CharField(blank=True, max_length=500, null=True)),
                ("start_date", models.DateField(auto_now_add=True)),
                ("comments", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "referred_by",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InformationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=254, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
