# Generated by Django 4.1.5 on 2023-02-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0021_rename_subscriber_informationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="contacted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="informationrequest",
            name="contacted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="informationrequest",
            name="notes",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
