# Generated by Django 4.1.5 on 2023-10-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0022_contact_contacted_contact_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="handle",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("philosophy", "Our Philosophy"),
                    ("classrooms", "Classrooms"),
                    ("steam", "S.T.E.A.M."),
                    ("preschool", "Preschool"),
                    ("school_age", "School Age"),
                    ("contact", "Contact"),
                    ("confirm", "Confirmation"),
                    ("employment", "Employment Information"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
