# Generated by Django 4.1.5 on 2023-11-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_page_meta_keywords_alter_page_meta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='keywords',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
