# Generated by Django 4.1.5 on 2023-11-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_remove_page_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(default='Empowering the Young Minds of Kalamazoo with Quality Childcare', max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(default="Here at The Village, we choose to focus on each individual's strengths rather than their weaknesses. Our childcare philosophy is to provide an age-appropriate environment that develops self-esteem, confidence, and a love of learning.", max_length=300),
        ),
        migrations.AlterField(
            model_name='page',
            name='keywords',
            field=models.TextField(default='childcare, daycare, preschool, school age, kalamazoo, michigan, steam, science, technology, engineering, art, math, education, learning, fun, play, kids, children, infant, toddler, pre-k, pre-k, pre-kindergarten, kindergarten, elementary, after school, before school, summer camp, summer, camp, summer program, summer programs, summer childcare, summer daycare, summer child care, summer day care, summercamp', max_length=800),
        ),
    ]
