# Generated by Django 4.1.5 on 2023-11-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_page_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(default='The Village Childcare: Empowering the Young Minds of Kalamazoo with Quality child care', max_length=255),
        ),
    ]
