# Generated by Django 4.1.5 on 2023-01-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_fname_customuser_lname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="fname",
            field=models.CharField(
                default="Jane", max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="lname",
            field=models.CharField(
                default="Doe", max_length=150, verbose_name="last name"
            ),
        ),
    ]
