# Generated by Django 4.1.5 on 2023-01-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_email_alter_customuser_fname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="fname",
            field=models.CharField(max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="lname",
            field=models.CharField(max_length=150, verbose_name="last name"),
        ),
    ]
